### ISSUE TITLE
获取appkey

### ISSUE THREAD

**Issue by Naeyoon** [songyangzz/QuantumultX#1]
从哪获取想要测试的应用程序的appkey  js文件中 有哪些是需要修改的呢

**Comment by songyangzz** [comment]
appkey是testfilght链接的url最后几位，只需要把你监控的key都填进去就行了

**Comment by lw0941** [comment]
> appkey是testfilght链接的url最后几位，只需要把你监控的key都填进去就行了

嗯 我知道appley是那个app链接最后的几个字符  例如QX的就是VCIvwk2g， 但假如前提是，没有收到开发者的测试邀请链接或者没有在网上找到公测链接，我又想要获取一个app的tf 我如何得知它的appkey

**Comment by lw0941** [comment]
还有一个问题，就是一个app的appkey是唯一的吗 还是说这个appkey只是对应app的某一个版本

**Comment by songyangzz** [comment]
都写了是公测。你不知道链接怎么监测呢？前提你先找到testflight的连接再监测。

**Comment by Chen3665** [comment]
在哪里能找到app公测链接 比如说 网站 或公众号什么的

**Comment by songyangzz** [comment]
> 在哪里能找到app公测链接 比如说 网站 或公众号什么的

tg频道

**Comment by Chen3665** [comment]
Thank you

songyangzz <notifications@github.com> 于2020年9月14日周一 下午9:09写道：

**Comment by lw0941** [comment]
> 从哪获取想要测试的应用程序的appkey js文件中 有哪些是需要修改的呢

**Comment by lw0941** [comment]
a
