### ISSUE TITLE
中青自动阅读的通知消息可以关闭吗？

### ISSUE THREAD

**Issue by chzzfly** [songyangzz/QuantumultX#14]
大佬您好，感谢您的脚本，用着很开心，不过自动阅读频繁不间断的通知提示烦不胜烦，可以设置为静默运行吗？谢谢。

**Comment by songyangzz** [comment]
> 大佬您好，感谢您的脚本，用着很开心，不过自动阅读频繁不间断的通知提示烦不胜烦，可以设置为静默运行吗？谢谢。

已加.boxjs更新可以开关

**Comment by chzzfly** [comment]
> > 大佬您好，感谢您的脚本，用着很开心，不过自动阅读频繁不间断的通知提示烦不胜烦，可以设置为静默运行吗？谢谢。
> 
> 已加.boxjs更新可以开关

刚试了一下，“静默运行”已经勾选，并且重启了 loon 软件，但还是有通知。
我看描述为“运行脚本时不发出系统弹窗通知”，不过横幅通知、声音通知，通知中心还是不停地显示通知。
请大佬测试一下。

**Comment by songyangzz** [comment]
> > > 大佬您好，感谢您的脚本，用着很开心，不过自动阅读频繁不间断的通知提示烦不胜烦，可以设置为静默运行吗？谢谢。
> 
> > 
> 
> > 已加.boxjs更新可以开关
> 
> 
> 
> 刚试了一下，“静默运行”已经勾选，并且重启了 loon 软件，但还是有通知。
> 
> 我看描述为“运行脚本时不发出系统弹窗通知”，不过横幅通知、声音通知，通知中心还是不停地显示通知。
> 
> 请大佬测试一下。

你得更新下脚本啊.我测了可以的啊

**Comment by chzzfly** [comment]
> > > > 大佬您好，感谢您的脚本，用着很开心，不过自动阅读频繁不间断的通知提示烦不胜烦，可以设置为静默运行吗？谢谢。
> > 
> > 
> > > 
> > 
> > 
> > > 已加.boxjs更新可以开关
> > 
> > 
> > 刚试了一下，“静默运行”已经勾选，并且重启了 loon 软件，但还是有通知。
> > 我看描述为“运行脚本时不发出系统弹窗通知”，不过横幅通知、声音通知，通知中心还是不停地显示通知。
> > 请大佬测试一下。
> 
> 你得更新下脚本啊.我测了可以的啊

更新了就好了，Thanks♪(･ω･)
