### ISSUE TITLE
通知显示

### ISSUE THREAD

**Issue by Naoko-simple** [songyangzz/QuantumultX#2]
通知不能显示没有车位的TF，在日志里输出为
`2020/02/29 17:24:41:495  <console>    [QTXLogHelper] Log level - error.`
`2020/02/29 17:24:47:055  <console>    [JS Console]: 1`
`2020/02/29 17:24:47:056  <console>    [JS Console]: 0begin`
`2020/02/29 17:24:48:968  <console>    [JS Console]: -1`
`2020/02/29 17:24:48:972  <console>    [JS Console]: 暂无车位`

**Comment by songyangzz** [comment]
刚更新了脚本，再试试吧

**Comment by Naoko-simple** [comment]
成功运行，谢谢。😊还有你注释那里的表达应该是“仍然”吧，你写成了“任然”。
