### ISSUE TITLE
"饿了么" app(9.0.10) "我的 - 打卡领红包"自动打卡

### ISSUE THREAD

**Issue by zZPiglet** [songyangzz/QuantumultX#4]
据[群友](https://t.me/joinchat/JikZ61Y-WyLUu6dBFPfu6w)反馈，新版饿了么加入新的打卡领红包接口。我大致[尝试了一下](https://raw.githubusercontent.com/zZPiglet/Task/master/elem/elemCheckIn.js)，只需要用到 Cookie 即可。不过还有宝箱之类的我没有去做，群友也希望您能将其整合加入原脚本，故提此 issue。

**Comment by songyangzz** [comment]
> 据[群友](https://t.me/joinchat/JikZ61Y-WyLUu6dBFPfu6w)反馈，新版饿了么加入新的打卡领红包接口。我大致[尝试了一下](https://raw.githubusercontent.com/zZPiglet/Task/master/elem/elemCheckIn.js)，只需要用到 Cookie 即可。不过还有宝箱之类的我没有去做，群友也希望您能将其整合加入原脚本，故提此 issue。

我的饿了么还没有这个活动.等都出来了.在整合吧.先用你的两个签呗.
